# Site settings
title: Haresh Khanna
description: 'Programmer Developer Foodie'
url: 'http://hareshkh.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'hareshkh'

author:
  name: 'Haresh Khanna'
  email: khanna.haresh@yahoo.co.in
  twitter_username: haresh_kh
  facebook_username: hareshkhanna01
  github_username:  hareshkh
  linkedin_username:  hareshkh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/ :month/ :day/ :title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
